name: Build and Publish Documentation

on:
  push:
    tags:
      - "v*.*.*" # Runs when a version tag (e.g., v1.0.0) is pushed
  workflow_dispatch: # Allows manual trigger from GitHub UI

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    permissions:
      id-token: write
      pages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown,x86_64-pc-windows-gnu

      - name: Build Documentationrun
        run: |
          touch assets/tailwind.css # stub generated asset
          cargo doc \
            --no-deps \
            --features server,web
          echo '<meta http-equiv="refresh" content="0;url=/tsto_server/tsto_server">' > target/doc/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "target/doc"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
